"use client";
import type {Metadata} from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/redux-provider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ReduxProvider>
			<html lang="en">
				<head>
					<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" />
					<link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css" />
					<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
				</head>
				<body className={inter.className}>{children}</body>
			</html>
		</ReduxProvider>
	);
}
